num1=int(input("Enter the first number"))
num2=int(input("enter the second number"))
print("addition=",num1+num2)
print("substraction=",num1-num2)
print("multiplication=",num1*num2)
print("division=",num1/num2)